### ISSUE TITLE
nameserver ipv6

### ISSUE THREAD

**Issue by bastard** [openlab-aux/labnetz-doku#4]
The nameserver doesn't deliver ipv4 adresses when there are no ipv6 entries. I.e. ask for print.openlab.lan - there is no answer.

**Comment by pRiVi** [comment]
print.openlab.lan does only have ipv4 entries in nameserver. Further here is no ipv6 DNS Server, so I don't understand the problem.

Maybe that there is no ipv6 DNS is the problem?
